### ISSUE TITLE
Organize several different graphql endpoints based on permissions

### ISSUE THREAD

**Issue by zadigus** [shopozor/services#50]
@donnerc came up with an interesting idea regarding the access to our graphql server: based on its credentials, a user would access some graphql endpoint with restricted api. Each endpoint needs a proper access token which can be delivered based on the user's permissions. For example, a Consumer would access the consumer endpoint, a Producer the producer endpoint. A Consumer who's not a Producer would not be able to login into the producer endpoint and issue producer API calls. The Consumer would have a much more restricted API than a Producer in that case. 

@shikamu how overkill is that, knowing that all the API calls are checked against the user's credentials? currently, if a user doesn't have the relevant credentials to make an API call, then she can't make it.

**Comment by zadigus** [comment]
@donnerc is that still necessary with hasura?

**Comment by donnerc** [comment]
This is not necessary anymore. Use access control is much more flexible with Hasura
