### ISSUE TITLE
autoformatting

### ISSUE THREAD

**Issue by donnerc** [shopozor/services#71]
Autoformatting should not only be enforced at pre-commit level but also when editting files. We should add a config file in order for VSCode to format the code consistently.

**Comment by zadigus** [comment]
Feel free to propose a linting configuration. Don't focus on VSCode though, as we will partially develop the project with Visual Studio too.

**Comment by zadigus** [comment]
On my development environment, I installed pylint which I think is used in VSCode.

**Comment by zadigus** [comment]
@donnerc any progress there? what are you missing exactly? I think IDE configuration is personal thing. It is the responsibility of the developers to make it comply to the automatic pre-commit hooks checks.
